@startuml
object User {
    UserId
    Password
    UserName
    Role
    Chatrooms[]
}
object frends {
    User1Id
    User2Id
}

object Chatroom {
    name
    ChatroomId
}

object Message {
    MessageId
    UserId
    ChatroomId
    Message
    TimeStamp
}

User - "*" Chatroom
Message -- User
Message -- Chatroom
frends "*"-"*" User
@enduml