@startuml
object User {
    UserId
    Password
    UserName
    Role
    Chatrooms[]
}

object Chatroom {
    name
    ChatroomId
}

object Message {
    MessageId
    UserId
    ChatroomId
    Message
    TimeStamp
}

User - "*" Chatroom
Message -- User
Message -- Chatroom
@enduml