@startuml
object User {
    UserId
    Password
    UserName
    Role
    Chatrooms[]
}
object frends {
    User1Id
    User2Id
}

object Chatroom {
    name
    ChatroomId
    User[]
    Message[]
}

object Message {
    MessageId
    UserId
    Message
    TimeStamp
}

User - "*" Chatroom
Message -- User
Message "*"-- Chatroom
frends "*"-"*" User
@enduml